In [4]:
import torch
import dataset

In [5]:
from diffusion import sinusoidal_embedding

In [14]:
torch.tensor([[1], [2]]).shape

torch.Size([2, 1])

In [13]:
sinusoidal_embedding(torch.tensor([[1], [2]]).to('cuda'), 8)

torch.Size([2, 8])


tensor([[ 0.8415,  0.5403,  0.0998,  0.9950,  0.0100,  0.9999,  0.0010,  1.0000],
        [ 0.9093, -0.4161,  0.1987,  0.9801,  0.0200,  0.9998,  0.0020,  1.0000]],
       device='cuda:0')

In [21]:
def sinusoidal_embedding(timesteps, embedding_dim):
    tensor_timesteps = torch.tensor(timesteps, dtype=torch.float32).unsqueeze(1)
    half_dim = embedding_dim // 2
    emb = 10000 ** (2 * torch.arange(half_dim) / (half_dim - 1))
    #print(tensor_timesteps, emb)
    emb = tensor_timesteps / emb
    emb = torch.cat((torch.sin(emb), torch.cos(emb)), dim=-1)

    return emb

In [22]:
sinusoidal_embedding([1, 200], 16)

tensor([[ 8.4147e-01,  7.1906e-02,  5.1794e-03,  3.7276e-04,  2.6827e-05,
          1.9307e-06,  1.3895e-07,  1.0000e-08,  5.4030e-01,  9.9741e-01,
          9.9999e-01,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00],
        [-8.7330e-01,  9.6727e-01,  8.6032e-01,  7.4483e-02,  5.3654e-03,
          3.8614e-04,  2.7790e-05,  2.0000e-06,  4.8719e-01, -2.5374e-01,
          5.0976e-01,  9.9722e-01,  9.9999e-01,  1.0000e+00,  1.0000e+00,
          1.0000e+00]])

In [17]:
embedding_dim = 16
torch.arange(embedding_dim // 2)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
# stranger way
timesteps = torch.tensor([5, 10, 15]).unsqueeze(1)

half_dim = embedding_dim // 2

emb = torch.arange(half_dim, dtype=torch.float32)
emb = torch.exp(emb * -torch.log(torch.tensor(10000.0)) / (half_dim - 1))
emb = timesteps[:, None] * emb[None, :]
emb = torch.cat((torch.sin(emb), torch.cos(emb)), dim=-1)
strange = emb

In [3]:
timesteps = torch.tensor([5, 10, 15]).unsqueeze(1)
timesteps.shape

torch.Size([3, 1])

In [37]:
# ez way
embedding_dim = 10
pe = torch.zeros((timesteps.shape[0], embedding_dim)).to('cuda')
print(pe.shape)

#timesteps = torch.tensor([1,2,3,4,5,6,7,8,9,10]).unsqueeze(1)
timesteps = torch.arange(1, 100).unsqueeze(1).to('cuda')
print(timesteps.shape)

indices = torch.arange(0, embedding_dim//2).to('cuda')

pe[:, 0::2] = torch.sin((timesteps)/torch.tensor(10000.).pow(2*indices/embedding_dim))
pe[:, 1::2] = torch.cos((timesteps)/torch.tensor(10000.).pow(2*indices/embedding_dim))
pe
# half_dim = embedding_dim // 2
# emb = 10000 ** (torch.arange(half_dim, dtype=torch.float32) / (half_dim - 1))

# emb = timesteps / emb

# ez = torch.cat((torch.sin(emb), torch.cos(emb)), dim=-1)


torch.Size([99, 10])
torch.Size([99, 1])


tensor([[ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
          9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
          9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
          9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
          9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00],
        [-9.5892e-01,  2.8366e-01,  7.1207e-01,  7.0211e-01,  1.2526e-01,
          9.9212e-01,  1.9904e-02,  9.9980e-01,  3.1548e-03,  1.0000e+00],
        [-2.7942e-01,  9.6017e-01,  8.1396e-01,  5.8092e-01,  1.5014e-01,
          9.8866e-01,  2.3884e-02,  9.9971e-01,  3.7857e-03,  9.9999e-01],
        [ 6.5699e-01,  7.5390e-01,  8.9544e-01,  4.4518e-01,  1.7493e-01,
          9.8458e-01,  2.7864e-0

In [27]:
ez[0].unsqueeze(-1).unsqueeze(-1).expand((16, 64, 64)).shape

torch.Size([16, 64, 64])

In [8]:
bt = 1 - torch.cos(torch.pi / 2 * torch.tensor(1 / 1000)
bt

SyntaxError: '(' was never closed (3739847946.py, line 1)

In [15]:
ez[0], strange[0]

(tensor([-9.5892e-01,  9.7379e-01,  3.5213e-01,  9.6385e-02,  2.5894e-02,
          6.9474e-03,  1.8638e-03,  5.0000e-04,  2.8366e-01,  2.2744e-01,
          9.3595e-01,  9.9534e-01,  9.9966e-01,  9.9998e-01,  1.0000e+00,
          1.0000e+00]),
 tensor([[-9.5892e-01,  9.7379e-01,  3.5213e-01,  9.6385e-02,  2.5894e-02,
           6.9474e-03,  1.8638e-03,  5.0000e-04,  2.8366e-01,  2.2744e-01,
           9.3595e-01,  9.9534e-01,  9.9966e-01,  9.9998e-01,  1.0000e+00,
           1.0000e+00]]))