In [1]:
import torch

In [21]:
def sinusoidal_embedding(timesteps, embedding_dim):
    tensor_timesteps = torch.tensor(timesteps, dtype=torch.float32).unsqueeze(1)
    half_dim = embedding_dim // 2
    emb = 10000 ** (2 * torch.arange(half_dim) / (half_dim - 1))
    #print(tensor_timesteps, emb)
    emb = tensor_timesteps / emb
    emb = torch.cat((torch.sin(emb), torch.cos(emb)), dim=-1)

    return emb

In [22]:
sinusoidal_embedding([1, 200], 16)

tensor([[ 8.4147e-01,  7.1906e-02,  5.1794e-03,  3.7276e-04,  2.6827e-05,
          1.9307e-06,  1.3895e-07,  1.0000e-08,  5.4030e-01,  9.9741e-01,
          9.9999e-01,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00],
        [-8.7330e-01,  9.6727e-01,  8.6032e-01,  7.4483e-02,  5.3654e-03,
          3.8614e-04,  2.7790e-05,  2.0000e-06,  4.8719e-01, -2.5374e-01,
          5.0976e-01,  9.9722e-01,  9.9999e-01,  1.0000e+00,  1.0000e+00,
          1.0000e+00]])

In [17]:
embedding_dim = 16
torch.arange(embedding_dim // 2)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
# stranger way
timesteps = torch.tensor([5, 10, 15]).unsqueeze(1)

half_dim = embedding_dim // 2

emb = torch.arange(half_dim, dtype=torch.float32)
emb = torch.exp(emb * -torch.log(torch.tensor(10000.0)) / (half_dim - 1))
emb = timesteps[:, None] * emb[None, :]
emb = torch.cat((torch.sin(emb), torch.cos(emb)), dim=-1)
strange = emb

In [18]:
# ez way
timesteps = torch.tensor([5, 10, 15]).unsqueeze(1)

half_dim = embedding_dim // 2
emb = 10000 ** (torch.arange(half_dim, dtype=torch.float32) / (half_dim - 1))

emb = timesteps / emb

ez = torch.cat((torch.sin(emb), torch.cos(emb)), dim=-1)



In [27]:
ez[0].unsqueeze(-1).unsqueeze(-1).expand((16, 64, 64)).shape

torch.Size([16, 64, 64])

In [15]:
ez[0], strange[0]

(tensor([-9.5892e-01,  9.7379e-01,  3.5213e-01,  9.6385e-02,  2.5894e-02,
          6.9474e-03,  1.8638e-03,  5.0000e-04,  2.8366e-01,  2.2744e-01,
          9.3595e-01,  9.9534e-01,  9.9966e-01,  9.9998e-01,  1.0000e+00,
          1.0000e+00]),
 tensor([[-9.5892e-01,  9.7379e-01,  3.5213e-01,  9.6385e-02,  2.5894e-02,
           6.9474e-03,  1.8638e-03,  5.0000e-04,  2.8366e-01,  2.2744e-01,
           9.3595e-01,  9.9534e-01,  9.9966e-01,  9.9998e-01,  1.0000e+00,
           1.0000e+00]]))